$schema: https://azuremlschemas.azureedge.net/latest/autoMLJob.schema.json
type: automl

experiment_name: Default
description: A classification AutoML job
display_name: eunsang_automl_job

task: classification

training_data:
  path: "https://inbreinazureml9455092953.blob.core.windows.net/azureml-blobstore-88907657-f5b2-4882-9898-7224649e9c1f/LocalUpload/e393d2d844017528b808d11cdf0ceb8a/iris.csv"
  type: mltable

compute: azureml:eunsang-ml-research

primary_metric: accuracy
target_column_name: y
n_cross_validations: 5

limits:
  timeout_minutes: 600
  trial_timeout_minutes: 20
  max_trials: 5
  enable_early_termination: True

training:
  blocked_training_algorithms: ["logistic_regression"]
  enable_onnx_compatible_models: True
