$schema: https://azuremlsdk2.blob.core.windows.net/preview/0.0.1/autoMLJob.schema.json
type: automl

experiment_name: Default
description: A classification AutoML job
task: classification

training_data:
    path: "/app/datasets/iris.csv"
    type: mltable

compute: azureml:eunsang-ml-research
primary_metric: accuracy  
target_column_name: y
n_cross_validations: 5

limits:
    timeout_minutes: 600 
    trial_timeout_minutes: 20 
    max_trials: 5
    enable_early_termination: True

training:
    blocked_training_algorithms: ["logistic_regression"] 
    enable_onnx_compatible_models: True
