$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: inbrein-iris-automl-best-model-endpoint-eunsang
endpoint_name: system-assigned-endpoint-with-auto-ml-best-model
model:
  path: ./downloaded_artifacts/named-outputs/best_model/
# TODO 
# code_configuration:
#   code: ../../model-1/onlinescoring/
#   scoring_script: score.py
environment: 
  conda_file: ./downloaded_artifacts/named-outputs/best_model/conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS3_v2
instance_count: 1
