$schema: https://azuremlschemas.azureedge.net/latest/model.schema.json
name: register-model-from-artifact
path: ../../app/configs/downloaded_artifacts/named-outputs/best_model/model.pkl
description: Register an automl model from train artifact 
