$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: simple_cron_job_schedule
display_name: Simple cron job schedule
description: A simple hourly cron job schedule

trigger:
  type: cron
  expression: "0 */2 * * *"   # every 2 hours

create_job: ./simple-pipeline-job.yml

inputs:
  hello_string_top_level_input: "hello world"
  azure_client_id: ""         
  azure_client_secret: ""     
  azure_tenant_id: ""         
