$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: simple_cron_job_schedule
display_name: Simple cron job schedule
description: a simple hourly cron job schedule

trigger:
  type: cron
  expression: "0 */2 * * *"   # at every 2nd hour 
 
create_job: ./simple-pipeline-job.yml
