$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_abc
compute: azureml:eunsang-ml-research
  
inputs:
  hello_string_top_level_input: "hello world"
  
jobs:
  a:
    command: echo hello ${{inputs.hello_string}}
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      hello_string: ${{parent.inputs.hello_string_top_level_input}}
  
  b:
    command: echo "world" >> ${{outputs.world_output}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    outputs:
      world_output:
  
  c:
    command: echo ${{inputs.world_input}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      world_input: ${{parent.jobs.b.outputs.world_output}}
      
  d:
    command: |
      # see if authenticated 
      az account show
      
      # Example: List datasets in the Azure ML workspace
      az ml data list --workspace-name your_workspace --resource-group your_resource_group
    environment: 
      image: eunsangacr.azurecr.io/azureml-with-azcli:latest  # Referencing the ACR image
