$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_abc
compute: azureml:eunsang-ml-research

inputs:
  hello_string_top_level_input: "hello world"

jobs:
  a:
    command: echo hello ${{inputs.hello_string}}
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      hello_string: ${{parent.inputs.hello_string_top_level_input}}

  b:
    command: echo "world" >> ${{outputs.world_output}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    outputs:
      world_output:

  c:
    command: echo ${{inputs.world_input}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      world_input: ${{parent.jobs.b.outputs.world_output}}

  d:
    command: |
      # Authenticate with Azure
      az login --service-principal -u 92e77697-5e5b-435e-8c8e-b3524e21a8ce -p 1fR8Q~fCCxSyxONCREmbXVWITmnpz_xVvHV6nb6o --tenant 5e0527d0-b0a8-46e9-b753-db3f51fb4dc2
      
      # Verify authentication
      az account show
      
      # Create dataset 
      az ml data create --name iris-dataset \
        --path ./datasets/iris.csv \
        --type uri_file \
        --workspace-name inbrein-azure-ml-research-eunsang \
        --resource-group inbrein-azure-ml-research
      
      # Example: List datasets in the Azure ML workspace
      az ml data list --workspace-name inbrein-azure-ml-research-eunsang --resource-group inbrein-azure-ml-research
    environment: 
      image: eunsangacr.azurecr.io/azureml-with-azcli:latest  # Referencing the ACR image
