name: Talk to the deployed Azure ML endpoint    

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run JavaScript with GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            // Request data goes here
            const requestBody = `[
              {"c1": 5.0, "c2": 3.3, "c3": 1.4, "c4": 0.2, "y": "Iris-setosa"},
              {"c1": 7.0, "c2": 3.2, "c3": 4.7, "c4": 1.4, "y": "Iris-versicolor"},
              {"c1": 5.1, "c2": 2.5, "c3": 3.0, "c4": 1.1, "y": "Iris-versicolor"},
              {"c1": 5.4, "c2": 3.9, "c3": 1.7, "c4": 0.4, "y": "Iris-setosa"},
              {"c1": 4.6, "c2": 3.1, "c3": 1.5, "c4": 0.2, "y": "Iris-setosa"},
              {"c1": 5.8, "c2": 2.6, "c3": 4.0, "c4": 1.2, "y": "Iris-versicolor"},
              {"c1": 5.0, "c2": 3.6, "c3": 1.4, "c4": 0.2, "y": "Iris-setosa"},
              {"c1": 5.6, "c2": 3.0, "c3": 4.5, "c4": 1.5, "y": "Iris-versicolor"},
              {"c1": 6.5, "c2": 3.0, "c3": 5.2, "c4": 2.0, "y": "Iris-virginica"},
              {"c1": 6.7, "c2": 3.1, "c3": 4.7, "c4": 1.5, "y": "Iris-versicolor"},
              {"c1": 5.1, "c2": 3.8, "c3": 1.5, "c4": 0.3, "y": "Iris-setosa"},
              {"c1": 6.3, "c2": 2.5, "c3": 4.9, "c4": 1.5, "y": "Iris-versicolor"},
              {"c1": 6.2, "c2": 2.8, "c3": 4.8, "c4": 1.8, "y": "Iris-versicolor"},
              {"c1": 7.2, "c2": 3.6, "c3": 6.1, "c4": 2.5, "y": "Iris-virginica"}
            ]
            `;

            const requestHeaders = new Headers({"Content-Type" : "application/json"});

            // Retrieve the API key from the environment variable
            const apiKey = process.env.ENDPOINT_PRIMARY_KEY;
            if (!apiKey) {
              throw new Error("A key should be provided to invoke the endpoint");
            }
            requestHeaders.append("Authorization", "Bearer " + apiKey);

            // This header will force the request to go to a specific deployment.
            requestHeaders.append("azureml-model-deployment", "model-deployment-eunsang");
            
            const url = "https://endpoint-eunsang.koreacentral.inference.ml.azure.com/score";
            
            fetch(url, {
              method: "POST",
              body: requestBody,
              headers: requestHeaders
            })
              .then((response) => {
                if (response.ok) {
                  return response.json();
                } else {
                  // Print the headers - they include the request ID and the timestamp, which are useful for debugging the failure
                  console.debug(...response.headers);
                  console.debug(response.body);
                  throw new Error("Request failed with status code " + response.status);
                }
              })
              .then((json) => console.log(json))
              .catch((error) => {
                console.error(error);
              });
        env:
          ENDPOINT_PRIMARY_KEY: ${{ secrets.ENDPOINT_PRIMARY_KEY }}
