name: Talk to the deployed Azure ML endpoint    

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run JavaScript with GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            // Request data goes here
            const requestBody = JSON.stringify(
                {"c1": 4.6, "c2": 3.2, "c3": 1.4, "c4": 0.2},  // No "y" for prediction requests
                {"c1": 5.3, "c2": 3.7, "c3": 1.5, "c4": 0.2},
                {"c1": 5.0, "c2": 3.3, "c3": 1.4, "c4": 0.2},
                {"c1": 7.0, "c2": 3.2, "c3": 4.7, "c4": 1.4},
                {"c1": 6.4, "c2": 3.2, "c3": 4.5, "c4": 1.5},
                {"c1": 5.7, "c2": 2.8, "c3": 4.1, "c4": 1.3},
                {"c1": 6.3, "c2": 3.3, "c3": 6.0, "c4": 2.5},
                {"c1": 5.8, "c2": 2.7, "c3": 5.1, "c4": 1.9},
                {"c1": 7.1, "c2": 3.0, "c3": 5.9, "c4": 2.1},
                {"c1": 6.3, "c2": 2.9, "c3": 5.6, "c4": 1.8}
            );
            
            const requestHeaders = new Headers({"Content-Type" : "application/json"});

            // Retrieve the API key from the environment variable
            const apiKey = process.env.ENDPOINT_PRIMARY_KEY;
            if (!apiKey) {
              throw new Error("A key should be provided to invoke the endpoint");
            }
            requestHeaders.append("Authorization", "Bearer " + apiKey);

            // This header will force the request to go to a specific deployment.
            requestHeaders.append("azureml-model-deployment", "model-deployment-eunsang");
            
            const url = "https://endpoint-eunsang.koreacentral.inference.ml.azure.com/score";
            
            fetch(url, {
              method: "POST",
              body: requestBody,
              headers: requestHeaders
            })
              .then((response) => {
                if (response.ok) {
                  return response.json();
                } else {
                  // Print the headers - they include the request ID and the timestamp, which are useful for debugging the failure
                  console.debug(...response.headers);
                  console.debug(response.body);
                  throw new Error("Request failed with status code " + response.status);
                }
              })
              .then((json) => console.log(json))
              .catch((error) => {
                console.error(error);
              });
        env:
          ENDPOINT_PRIMARY_KEY: ${{ secrets.ENDPOINT_PRIMARY_KEY }}
