name: Talk to the deployed Azure ML endpoint    

on:
  workflow_dispatch:
  
jobs:
  send-score-request:   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Log in to Azure CLI
      uses: azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure ML CLI extension
      run: |
        az extension add -n ml

    - name: Send Score Request
      run: |
        az ml online-endpoint invoke \
          --name endpoint-eunsang \
          --request-file ./configs/Azure-CLI-Environment/iris-test.json \
          --resource-group inbrein-azure-ml-research \
          --workspace-name inbrein-azure-ml-research-eunsang
