name: Talk to the deployed Azure ML endpoint    

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run JavaScript with GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            // Request data goes here
            const requestBody = JSON.stringify({
              data: [
                {"sepal_length": 5.1, "sepal_width": 2.5, "petal_length": 3.0, "petal_width": 1.1},
                {"sepal_length": 5.7, "sepal_width": 2.8, "petal_length": 4.1, "petal_width": 1.3},
                {"sepal_length": 6.3, "sepal_width": 3.3, "petal_length": 6.0, "petal_width": 2.5},
                {"sepal_length": 5.8, "sepal_width": 2.7, "petal_length": 5.1, "petal_width": 1.9},
                {"sepal_length": 7.1, "sepal_width": 3.0, "petal_length": 5.9, "petal_width": 2.1},
                {"sepal_length": 6.3, "sepal_width": 2.9, "petal_length": 5.6, "petal_width": 1.8},
                {"sepal_length": 6.5, "sepal_width": 3.0, "petal_length": 5.8, "petal_width": 2.2},
                {"sepal_length": 7.6, "sepal_width": 3.0, "petal_length": 6.6, "petal_width": 2.1},
                {"sepal_length": 4.9, "sepal_width": 2.5, "petal_length": 4.5, "petal_width": 1.7},
                {"sepal_length": 7.3, "sepal_width": 2.9, "petal_length": 6.3, "petal_width": 1.8},
                {"sepal_length": 6.7, "sepal_width": 2.5, "petal_length": 5.8, "petal_width": 1.8},
                {"sepal_length": 7.2, "sepal_width": 3.6, "petal_length": 6.1, "petal_width": 2.5},
                {"sepal_length": 6.5, "sepal_width": 3.2, "petal_length": 5.1, "petal_width": 2.0},
                {"sepal_length": 6.4, "sepal_width": 2.7, "petal_length": 5.3, "petal_width": 1.9},
                {"sepal_length": 6.8, "sepal_width": 3.0, "petal_length": 5.5, "petal_width": 2.1}
              ]
            });
            
            const requestHeaders = new Headers({"Content-Type" : "application/json"});

            // Retrieve the API key from the environment variable
            const apiKey = process.env.ENDPOINT_PRIMARY_KEY;
            if (!apiKey) {
              throw new Error("A key should be provided to invoke the endpoint");
            }
            requestHeaders.append("Authorization", "Bearer " + apiKey);

            // This header will force the request to go to a specific deployment.
            requestHeaders.append("azureml-model-deployment", "model-deployment-eunsang");
            
            const url = "https://endpoint-eunsang.koreacentral.inference.ml.azure.com/score";
            
            fetch(url, {
              method: "POST",
              body: requestBody,
              headers: requestHeaders
            })
              .then((response) => {
                if (response.ok) {
                  return response.json();
                } else {
                  // Print the headers - they include the request ID and the timestamp, which are useful for debugging the failure
                  console.debug(...response.headers);
                  console.debug(response.body);
                  throw new Error("Request failed with status code " + response.status);
                }
              })
              .then((json) => console.log(json))
              .catch((error) => {
                console.error(error);
              });
        env:
          ENDPOINT_PRIMARY_KEY: ${{ secrets.ENDPOINT_PRIMARY_KEY }}
